version: '3'
services:
  cassandra:
    image: cassandra
    container_name: cwai-cassandra
    ports:
      - 9042:9042
    volumes:
      - ./cassandra:/cassandra
    command: /bin/sh /cassandra/init.sh

  product-service:
    container_name: cwai-product-service
    build:
      context: ..
      dockerfile: docker/product-service/Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
    depends_on:
      - cassandra
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cassandra 9042); do sleep 5; echo 'Waiting for cassandra to start-up...'; done;
      java -Dcom.sun.management.jmxremote=true \
           -Dcom.sun.management.jmxremote.rmi.port=9090 \
           -Dcom.sun.management.jmxremote.port=9090 \
           -Dcom.sun.management.jmxremote.ssl=false \
           -Dcom.sun.management.jmxremote.authenticate=false \
           -Dcom.sun.management.jmxremote.local.only=false \
           -Djava.rmi.server.hostname=localhost \
           -Dspring.profiles.active=docker \
           -jar /app.jar
      "